FROM httpd:2.4

EXPOSE 80/tcp

VOLUME /usr/local/apache2/cgi-bin

#COPY httpd/public-html/ . /usr/local/apache2/htdocs/
COPY bin/* /usr/local/apache2/cgi-bin/
COPY httpd/httpd.conf /usr/local/apache2/conf/httpd.conf
