FROM httpd:2.4

EXPOSE 80/tcp
RUN apt-get update && apt-get install -y libglib2.0-0 libjansson4 libpq5
VOLUME /usr/local/apache2/cgi-bin

#COPY httpd/public-html/ . /usr/local/apache2/htdocs/
COPY bin/* /usr/local/apache2/cgi-bin/
COPY httpd/httpd.conf /usr/local/apache2/conf/httpd.conf
